# Generated by Django 4.2 on 2023-04-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.departamento'),
        ),
    ]
